### ISSUE TITLE
Support mutation?

### ISSUE THREAD

**Issue by joonhocho** [sazzer/graphql-tester#5]
Any plans to support mutations?

**Comment by sazzer** [comment]
Any reason why you can't use it for mutations as-is? It currently just
sends arbitrary requests to the server and a mutation is just how you write
the request...
On 11 Jun 2016 07:17, "Joon Ho Cho" notifications@github.com wrote:

Any plans to support mutations?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/sazzer/graphql-tester/issues/5, or mute the thread
https://github.com/notifications/unsubscribe/AAECGO2Dk4IzFSOGrWD87BsozkL739bnks5qKlLbgaJpZM4Ize7t
.

**Comment by joonhocho** [comment]
Sorry, you are right.
